### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by cyberblue1** [aodongli/zero-shot-ad-via-batch-norm#2]
bottle
DB: train 14 test 83

Process finished with exit code 137

How can I fix it?

**Comment by cyberblue1** [comment]
Traceback (most recent call last):
  File "/data/work_Space/mvtec-ad/main.py", line 73, in <module>
    res = run_dataset(dataset, env_config, model_config)
  File "/data/work_Space/mvtec-ad/main.py", line 44, in run_dataset
    eval_metrics = trainer.train(train_loader=dataset,
  File "/data/work_Space/mvtec-ad/trainers/zeroshot_trainer.py", line 196, in train
    train_loss = self._train(iteration, train_loader, optimizer)
  File "/data/work_Space/mvtec-ad/trainers/zeroshot_trainer.py", line 39, in _train
    z, center = self.model(x)
  File "/home/ls/anaconda3/envs/clip2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/work_Space/mvtec-ad/models/feature_model.py", line 32, in forward
    z = self.enc(x)
  File "/home/ls/anaconda3/envs/clip2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ls/anaconda3/envs/clip2/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/ls/anaconda3/envs/clip2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ls/anaconda3/envs/clip2/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 94, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/ls/anaconda3/envs/clip2/lib/python3.8/site-packages/torch/nn/functional.py", line 1753, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 dim 1 must match mat2 dim 0

Process finished with exit code 1

it happend when I run resnet18 , how can I fix it?

**Comment by aodongli** [comment]
Resnet18 requires 224x224 input image size. Can you try whatever to crop your input image to size 224x224 and try again?
